[project]
name = "rag-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "roy-ayush22", email = "ayush30085@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
rag-from-scratch = "rag_from_scratch:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
